### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rayman** [Rayman/ros-get#3]
## Commands
- [ ] ws-create
  - [x] save ws under `~/.config/ros-get/`
  - [x] rosdistro url as argument
  - [ ] generate `setup.sh`
- [x] ws-save ?
- [x] ws-list
- [x] ws-switch
- [x] ws-locate
- ~[ ] ws-cleanup (maybe do it as part of list?)~ Moved to #74
- [x] install (mark as installed & update)
  - [x] recursive git clone
  - [x] mark as installed
  - [x] create symlinks from src to repos
  - [x] recursive checkout bug
- [x] update
  - [x] ~rosdistro pull~
  - [x] rosdep update
- [x] status
- [x] ~upgrade~
- [x] remove
- [x] ~autoremove~

## Questions
- ~create a new distro or overlay an existing one?~ (overlaying is a good solution and works fine)

## Installation
- ~[ ] installation should install /etc/ros/rosdep/sources.list.d/80*~
```
  sudo sh -c "echo \"yaml file://$HOME/.ros/ros-get/rosdistro/rosdep/ros-rosdistro-kinetic.yaml kinetic\" > /etc/ros/rosdep/sources.list.d/90-ros-rosdistro-kinetic.list"
  rosdep update
```
